import SwiftUI
import AVKit
import AVFoundation
import Combine

public struct ContentView: View {
    // Media URLs generated by MockAssetGenerator
    @State private var localAssets: [URL] = []
    @State private var isGeneratingAssets = false
    @State private var statusMessage = "Waiting to generate assets..."
    @State private var errorMessage: String? = nil
    
    // UI Playback States
    @State private var player = AVPlayer()
    @State private var currentTimeline = Timeline()
    
    // Pipeline Controls
    @State private var enableTransforms = true
    @State private var enableColorAdjustments = true
    @State private var activeFilter: CIFilterType = .none
    @State private var activeLUT: LUTType = .none
    @State private var enablePIPOverlay = true
    @State private var enableSticker = true
    @State private var enableText = true
    @State private var transitionType: TransitionType = .crossfade
    @State private var transitionDuration: Double = 1.5
    @State private var timelineFPS = 60
    @State private var canvasResolution: CanvasResolution = .p4kLandscape
    
    // Export States
    @State private var isExporting = false
    @State private var exportProgress: Float = 0.0
    @State private var exportedVideoURL: URL? = nil
    @State private var showExportPreview = false
    
    public init() {}
    
    public var body: some View {
        ZStack {
            Color(UIColor.systemBackground)
                .ignoresSafeArea()
            
            if isGeneratingAssets {
                VStack(spacing: 20) {
                    ProgressView()
                        .scaleEffect(1.5)
                    Text("Synthesizing Mock Video Assets...")
                        .font(.headline)
                        .foregroundColor(.secondary)
                    Text(statusMessage)
                        .font(.caption)
                        .foregroundColor(.gray)
                        .multilineTextAlignment(.center)
                        .padding(.horizontal)
                }
            } else if let error = errorMessage {
                VStack(spacing: 20) {
                    Image(systemName: "exclamationmark.triangle.fill")
                        .font(.system(size: 50))
                        .foregroundColor(.red)
                    Text("An Error Occurred")
                        .font(.title2)
                        .fontWeight(.bold)
                    Text(error)
                        .font(.body)
                        .foregroundColor(.secondary)
                        .multilineTextAlignment(.center)
                        .padding(.horizontal)
                    Button("Retry Asset Generation") {
                        generateAssets()
                    }
                    .buttonStyle(.borderedProminent)
                }
            } else {
                ScrollView {
                    VStack(alignment: .leading, spacing: 20) {
                        // 1. Title
                        HStack {
                            VStack(alignment: .leading, spacing: 4) {
                                Text("CoreImage & AVFoundation")
                                    .font(.caption)
                                    .fontWeight(.bold)
                                    .foregroundColor(.accentColor)
                                    .tracking(2)
                                Text("Video Editing Pipeline")
                                    .font(.title2)
                                    .fontWeight(.bold)
                            }
                            Spacer()
                            
                            Button(action: {
                                generateAssets()
                            }) {
                                Image(systemName: "arrow.triangle.2.circlepath")
                                    .font(.body)
                            }
                            .buttonStyle(.bordered)
                        }
                        .padding(.horizontal)
                        
                        // 2. Video Player Preview Area
                        VStack(spacing: 8) {
                            PlayerView(player: player)
                                .frame(height: 240)
                                .cornerRadius(12)
                                .shadow(color: Color.black.opacity(0.3), radius: 8, x: 0, y: 4)
                                .padding(.horizontal)
                            
                            HStack {
                                Text("Timeline Duration: 10s")
                                Spacer()
                                Text("Status: Ready")
                                    .foregroundColor(.green)
                            }
                            .font(.caption)
                            .foregroundColor(.secondary)
                            .padding(.horizontal, 24)
                        }
                        
                        // 3. Pipeline Editing Settings
                        VStack(alignment: .leading, spacing: 16) {
                            Text("Editing Settings (Mock parameters)")
                                .font(.headline)
                                .padding(.horizontal)
                            
                            TimelineSettingsView(
                                enableTransforms: $enableTransforms,
                                enableColorAdjustments: $enableColorAdjustments,
                                enablePIPOverlay: $enablePIPOverlay,
                                enableSticker: $enableSticker,
                                enableText: $enableText,
                                activeFilter: $activeFilter,
                                activeLUT: $activeLUT,
                                transitionType: $transitionType,
                                transitionDuration: $transitionDuration,
                                timelineFPS: $timelineFPS,
                                canvasResolution: $canvasResolution,
                                onChange: { reloadTimeline() }
                            )
                            .padding()
                            .background(Color(UIColor.secondarySystemBackground))
                            .cornerRadius(16)
                            .padding(.horizontal)
                        }
                        
                        // 4. Export Section
                        VStack(spacing: 12) {
                            if isExporting {
                                VStack(spacing: 8) {
                                    ProgressView(value: exportProgress, total: 1.0)
                                        .progressViewStyle(.linear)
                                    HStack {
                                        Text("Exporting timeline...")
                                        Spacer()
                                        Text(String(format: "%.0f%%", exportProgress * 100))
                                    }
                                    .font(.caption)
                                    .foregroundColor(.secondary)
                                }
                                .padding()
                                .background(Color(UIColor.secondarySystemBackground))
                                .cornerRadius(12)
                                .padding(.horizontal)
                            } else {
                                Button(action: {
                                    exportTimeline()
                                }) {
                                    HStack {
                                        Image(systemName: "square.and.arrow.up")
                                        Text("Export Editing Timeline to MP4")
                                            .fontWeight(.bold)
                                    }
                                    .frame(maxWidth: .infinity)
                                    .padding()
                                    .background(Color.accentColor)
                                    .foregroundColor(.white)
                                    .cornerRadius(12)
                                }
                                .padding(.horizontal)
                            }
                            
                            if let exportedURL = exportedVideoURL {
                                Button(action: {
                                    showExportPreview = true
                                }) {
                                    HStack {
                                        Image(systemName: "play.circle.fill")
                                        Text("Play Exported MP4 File")
                                            .fontWeight(.semibold)
                                    }
                                    .frame(maxWidth: .infinity)
                                    .padding()
                                    .background(Color(UIColor.systemGreen))
                                    .foregroundColor(.white)
                                    .cornerRadius(12)
                                }
                                .padding(.horizontal)
                                .sheet(isPresented: $showExportPreview) {
                                    ExportPreviewModal(videoURL: exportedURL)
                                }
                            }
                        }
                        .padding(.bottom, 30)
                    }
                }
            }
        }
        .onAppear {
            generateAssets()
        }
    }
    
    // MARK: - Actions
    
    private func generateAssets() {
        isGeneratingAssets = true
        errorMessage = nil
        statusMessage = "Starting Asset Writing..."
        
        MockAssetGenerator.shared.generateAllAssetsIfNeeded { result in
            DispatchQueue.main.async {
                isGeneratingAssets = false
                switch result {
                case .success(let urls):
                    self.localAssets = urls
                    self.statusMessage = "Assets ready!"
                    reloadTimeline()
                case .failure(let error):
                    self.errorMessage = "Failed to generate assets: \(error.localizedDescription)"
                }
            }
        }
    }
    private func reloadTimeline() {
        guard localAssets.count >= 3 else { return }
        
        let isPortraitCanvas = canvasResolution.size.height > canvasResolution.size.width
        
        let video1: URL
        let video2: URL
        let video3: URL
        
        if isPortraitCanvas {
            // For Portrait canvas, use portrait videos as primary clips
            video1 = localAssets[1] // woodland_woods.mp4
            video2 = localAssets[2] // vertical_content.mp4
            video3 = localAssets[0] // agent_4k.mp4
        } else {
            // For Landscape canvas, use landscape video as primary clips
            video1 = localAssets[0] // agent_4k.mp4
            video2 = localAssets[1] // woodland_woods.mp4
            video3 = localAssets[2] // vertical_content.mp4
        }
        
        // 1. Create clip 1 (Red / 5s)
        var clip1 = VideoClip(
            id: UUID(),
            sourceURL: video1,
            timelineTimeRange: CMTimeRange(start: .zero, duration: CMTime(seconds: 5.0, preferredTimescale: 600)),
            sourceTimeRange: CMTimeRange(start: .zero, duration: CMTime(seconds: 5.0, preferredTimescale: 600))
        )
        if enableTransforms {
            clip1.transform.scale = 1.15
            clip1.transform.rotation = 0.05
            clip1.crop = CropArea(x: 0.05, y: 0.05, width: 0.9, height: 0.9)
        }
        if enableColorAdjustments {
            clip1.colorAdjustments.brightness = 0.05
            clip1.colorAdjustments.contrast = 1.1
            clip1.colorAdjustments.saturation = 1.25
            clip1.colorAdjustments.exposure = 0.2
        }
        clip1.activeFilter = activeFilter
        clip1.activeLUT = activeLUT
        
        // 2. Create clip 2 (Blue / 5s)
        var clip2 = VideoClip(
            id: UUID(),
            sourceURL: video2,
            timelineTimeRange: CMTimeRange(start: CMTime(seconds: 5.0, preferredTimescale: 600), duration: CMTime(seconds: 5.0, preferredTimescale: 600)),
            sourceTimeRange: CMTimeRange(start: .zero, duration: CMTime(seconds: 5.0, preferredTimescale: 600))
        )
        if enableTransforms {
            clip2.transform.scale = 0.95
            clip2.transform.rotation = -0.05
        }
        if enableColorAdjustments {
            clip2.colorAdjustments.brightness = -0.05
            clip2.colorAdjustments.contrast = 1.2
            clip2.colorAdjustments.saturation = 0.9
            clip2.colorAdjustments.exposure = -0.1
        }
        clip2.activeFilter = (activeFilter == .none) ? .none : .vignette
        clip2.activeLUT = (activeLUT == .none) ? .none : .vibrant
        
        var timeline = Timeline()
        timeline.canvasResolution = canvasResolution
        timeline.fps = timelineFPS
        timeline.videoClips = [clip1, clip2]
        
        // 3. Create transition if active
        if transitionType != .none {
            let transition = Transition(
                id: UUID(),
                type: transitionType,
                duration: CMTime(seconds: transitionDuration, preferredTimescale: 600),
                atTime: CMTime(seconds: 5.0, preferredTimescale: 600)
            )
            timeline.transitions = [transition]
        }
        
        // 4. Create PIP Overlay video
        if enablePIPOverlay {
            let overlay = VideoOverlay(
                id: UUID(),
                sourceURL: video3,
                timelineTimeRange: CMTimeRange(start: CMTime(seconds: 1.5, preferredTimescale: 600), duration: CMTime(seconds: 5.0, preferredTimescale: 600)),
                sourceTimeRange: CMTimeRange(start: .zero, duration: CMTime(seconds: 3.0, preferredTimescale: 600)),
                rect: CGRect(x: 0.62, y: 0.05, width: 0.33, height: 0.33),
                opacity: 0.85,
                scale: 1.0,
                rotation: 0.1,
                blendMode: .sourceOver
            )
            timeline.videoOverlays = [overlay]
        }
        
        // 5. Create Sticker Overlay
        if enableSticker {
            let sticker = StickerOverlay(
                id: UUID(),
                systemImageName: "star.fill",
                timelineTimeRange: CMTimeRange(start: CMTime(seconds: 1.0, preferredTimescale: 600), duration: CMTime(seconds: 8.0, preferredTimescale: 600)),
                rect: CGRect(x: 0.05, y: 0.6, width: 0.12, height: 0.12),
                opacity: 0.9,
                scale: 1.0,
                rotation: 0.2
            )
            timeline.stickerOverlays = [sticker]
        }
        
        // 6. Create Text Overlay
        if enableText {
            let text = TextOverlay(
                id: UUID(),
                text: "PRO EDITING ENGINE",
                color: .cyan,
                fontSize: 24,
                timelineTimeRange: CMTimeRange(start: CMTime(seconds: 0.5, preferredTimescale: 600), duration: CMTime(seconds: 9.0, preferredTimescale: 600)),
                rect: CGRect(x: 0.1, y: 0.82, width: 0.8, height: 0.1),
                opacity: 0.9,
                scale: 1.0,
                rotation: 0.0
            )
            timeline.textOverlays = [text]
        }
        
        self.currentTimeline = timeline
        
        // Compile render graph in async Task
        Task {
            do {
                let result = try await TimelineCompositionBuilder.shared.buildComposition(from: timeline)
                
                await MainActor.run {
                    let playerItem = AVPlayerItem(asset: result.composition)
                    playerItem.videoComposition = result.videoComposition
                    playerItem.audioMix = result.audioMix
                    
                    let currentPlayhead = player.currentTime()
                    player.replaceCurrentItem(with: playerItem)
                    
                    if currentPlayhead.seconds > 0 && currentPlayhead.seconds < 10.0 {
                        player.seek(to: currentPlayhead, toleranceBefore: .zero, toleranceAfter: .zero)
                    }
                }
            } catch {
                await MainActor.run {
                    self.errorMessage = "Failed to build composition: \(error.localizedDescription)"
                }
            }
        }
    }
    
    private func exportTimeline() {
        guard localAssets.count >= 3 else { return }
        
        isExporting = true
        exportProgress = 0.0
        exportedVideoURL = nil
        
        Task {
            do {
                let result = try await TimelineCompositionBuilder.shared.buildComposition(from: currentTimeline)
                
                let fileManager = FileManager.default
                let outputURL = fileManager.temporaryDirectory.appendingPathComponent("high_bitrate_4k_60fps.mp4")
                try? fileManager.removeItem(at: outputURL)
                
                guard let exportSession = AVAssetExportSession(
                    asset: result.composition,
                    presetName: AVAssetExportPresetHighestQuality
                ) else {
                    await MainActor.run {
                        isExporting = false
                        errorMessage = "Failed to allocate AVAssetExportSession"
                    }
                    return
                }
                
                exportSession.videoComposition = result.videoComposition
                exportSession.audioMix = result.audioMix
                exportSession.shouldOptimizeForNetworkUse = true
                
                // Monitor the export states asynchronously (iOS 18+ API)
                let stateMonitorTask = Task {
                    for await state in exportSession.states(updateInterval: 0.1) {
                        if case .exporting(let progress) = state {
                            await MainActor.run {
                                self.exportProgress = Float(progress.fractionCompleted)
                            }
                        }
                    }
                }
                
                // Perform the export asynchronously (iOS 18+ API)
                try await exportSession.export(to: outputURL, as: .mp4)
                
                // Ensure the progress monitor is cancelled after completion
                stateMonitorTask.cancel()
                
                await MainActor.run {
                    self.isExporting = false
                    self.exportedVideoURL = outputURL
                    self.showExportPreview = true
                }
                
            } catch {
                await MainActor.run {
                    isExporting = false
                    self.errorMessage = "Export failed: \(error.localizedDescription)"
                }
            }
        }
    }
}
